apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "your-acm-cert-arn"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  selector:
    app: sentiment-analysis
  ports:
    - port: 443
      targetPort: 80
      protocol: TCP
  type: LoadBalancer