apiVersion: v1
kind: Service
metadata:
  name: sentiment-analysis-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-2:677276084635:certificate/df39088b-f003-46ef-8190-c022f909bf68"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  selector:
    app: sentiment-analysis
  ports:
    - port: 443
      targetPort: 80
      protocol: TCP
  type: LoadBalancer